[tool.black]
line-length = 100
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  # Exclude vendor directory
  | vendor
)
'''

[tool.isort]
line_length = 100
multi_line_output = 0
lines_after_imports = 2
skip_glob = [
  "**/.env*",
  "**/env/*",
  "**/.venv/*",
  "**/docs/*",
  "**/user_data/*",
  "**/__init__.py",
]
